[programs.localnet]
vvallet = "5EwrjHSsAiQjLmepCocQCEXuCe2wUZVjTaWM4jAim3Fo"

[programs.devnet]
vvallet = "5EwrjHSsAiQjLmepCocQCEXuCe2wUZVjTaWM4jAim3Fo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/bruce/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/vvallet.json app/src/idl/vvallet.json"
