version: '2.0'

services:
  db:
    image: postgres
    restart: always
    environment:
      # Set these in a .env file for your environment
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local
  vvallet:
    image: vvallet
    build: .
    depends_on:
      - db
    environment:
      # host=localhost user=postgres password=password dbname=postgres port=5432
      VVALLET_DSN: ${VVALLET_DSN}
      VVALLET_PLAINTEXT_PORT: ${VVALLET_PLAINTEXT_PORT}
      VVALLET_TLS_PORT: ${VVALLET_TLS_PORT}
      VVALLET_LOG_LEVEL: ${VVALLET_LOG_LEVEL}
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./certs:/root/certs
    networks:
      - local

networks:
  local:
    driver: bridge